import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import DogImage from '../components/DogImage'
import RemoteDogCaption from '../components/RemoteDogCaption'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        This dog is really cute, you should adopt this dog 
      </div>
      <div>
        <DogImage />
        <RemoteDogCaption name="Juchka"/>
      </div>
    </div>
  )
}

export default Home
